# Generated by Django 4.2.3 on 2023-08-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoListApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist", old_name="task", new_name="tasks",
        ),
    ]
